# Generated by Django 5.2.6 on 2025-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0008_alter_author_user_alter_book_user_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='livres', to='bonnes_lectures.author'),
        ),
    ]
