# Generated by Django 5.2.6 on 2025-11-17 15:41

import bonnes_lectures.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0009_remove_book_author_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=bonnes_lectures.fields.IsbnField(max_length=17),
        ),
    ]
